name = "positions-ws2"
main = "src/index.mjs"
compatibility_date = "2025-10-08"
workers_dev = true

[durable_objects]
bindings = [{ name = "POSITIONS_DO", class_name = "PositionsDO" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PositionsDO"]

